export const contactList = [
  {
    id: 1,
    name: "Ranjit kumar",
    profilePic: "/whatsapp-clone/profile/s.jpeg",
    lastText: "Hey Man whtas a problems",
    lastTextTime: "12:58 PM",
  },
  {
    id: 2,
    name: "yusuf hasan",
    profilePic:"/whatsapp-clone/whatsapp-clone/profile/yusuf.jfif",
    lastText: ` my best friend in coding life`,
    lastTextTime: "12:45 PM",
  },
  {
    id: 3,
    name: "vikash sir",
    profilePic: "/whatsapp-clone/whatsapp-clone/profile/vikas_sir.jfif",
    lastText: "you are my seniour?",
    lastTextTime: "12:30 PM",
  },
  {
    id: 4,
    name: "anjali somethings",
    profilePic: "/whatsapp-clone/profile/logo.png",
    lastText: "just for something",
    lastTextTime: "12:00 PM",
  },
  {
    id: 3,
    name: "shusil ",
    profilePic: "/whatsapp-clone/profile/logo.png",
    lastText: "i am intern bro",
    lastTextTime: "12:30 PM",
  },
  {
    id: 4,
    name: "rohit bansal",
    profilePic: "/whatsapp-clone/whatsapp-clone/profile/rohit.jfif",
    lastText: "gussa marne ka man karta hai kisi ko",
    lastTextTime: "12:00 PM",
  },
];
export const messagesList = [
  {
    id: 1,
    messageType: "ranjit hello",
    text: "ranjit Man 😁",
    senderID: 0,
    addedOn: "12:00 PM",
  },
  {
    id: 2,
    messageType: "TEXT",
    text: "Hey, What's up?",
    senderID: 1,
    addedOn: "12:01 PM",
  },
  {
    id: 3,
    messageType: "TEXT",
    text: "All Good, What about you?",
    senderID: 0,
    addedOn: "12:00 PM",
  },
  {
    id: 4,
    messageType: "TEXT",
    text: "I'm good as well",
    senderID: 1,
    addedOn: "12:00 PM",
  },
  {
    id: 5,
    messageType: "TEXT",
    text: "Great 😁",
    senderID: 0,
    addedOn: "12:00 PM",
  },
  {
    id: 5,
    messageType: "TEXT",
    text: "Have you subscribed The Indian Dev ?",
    senderID: 1,
    addedOn: "12:00 PM",
  },
];
